# 技能文档体量 + README 代码块配对检查
import os

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
files = [
    'entry/src/main/resources/rawfile/skills/svg/SKILL.md',
    'entry/src/main/resources/rawfile/skills/svg/reference/svg-craft.md',
    'entry/src/main/resources/rawfile/skills/svg/reference/svg-recipes.md',
    'entry/src/main/resources/rawfile/skills/ppt/SKILL.md',
    'entry/src/main/resources/rawfile/skills/ppt/reference/deck-dsl.md',
    'entry/src/main/resources/rawfile/skills/ppt/reference/design-guide.md',
    'entry/src/main/resources/rawfile/skills/ppt/reference/themes.md',
    'entry/src/main/resources/rawfile/skills/humanizer/SKILL.md',
    'entry/src/main/resources/rawfile/skills/humanizer/reference/general-patterns-2.md',
    'entry/src/main/resources/rawfile/skills/humanizer/reference/social-media.md',
    'entry/src/main/resources/rawfile/skills/humanizer/reference/readability.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/SKILL.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/BEST_PRACTICES.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/TECHNIQUES.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/TROUBLESHOOTING.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/EXAMPLES.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/START_HERE.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/GETTING_STARTED.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/SUMMARY.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/INDEX.md',
    'entry/src/main/resources/rawfile/skills/prompt-engineering/reference/CLAUDE.md',
    'entry/src/main/resources/rawfile/skills/pdf/SKILL.md',
    'entry/src/main/resources/rawfile/skills/pdf/reference/tool-notes.md',
    'entry/src/main/resources/rawfile/skills/translation/SKILL.md',
    'entry/src/main/resources/rawfile/skills/translation/reference/medical-1.md',
    'entry/src/main/resources/rawfile/skills/translation/reference/medical-2.md',
    'entry/src/main/resources/rawfile/skills/translation/reference/medical-3.md',
    'entry/src/main/resources/rawfile/skills/translation/reference/medical-4.md',
    'entry/src/main/resources/rawfile/skills/translation/reference/medical-5.md',
    'entry/src/main/resources/rawfile/skills/questionnaire/SKILL.md',
    'entry/src/main/resources/rawfile/skills/questionnaire/CHANGELOG.md',
    'entry/src/main/resources/rawfile/skills/questionnaire/references/m1-questionnaire-design.md',
    'entry/src/main/resources/rawfile/skills/questionnaire/references/m2-interview-outline.md',
    'entry/src/main/resources/rawfile/skills/questionnaire/references/m3-verbatim-tagging.md',
    'entry/src/main/resources/rawfile/skills/questionnaire/references/m4-quantitative-analysis.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/SKILL.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/cover-design-methodology.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/distribution-package-format.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/fact-check-and-compliance.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/image-generation.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/internet-search.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/output-standard.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/common/source-analysis.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/platforms/short-video.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/platforms/wechat.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/platforms/weibo.md',
    'entry/src/main/resources/rawfile/skills/content-rewrite/references/platforms/xhs.md',
    'entry/src/main/resources/rawfile/skills/html/SKILL.md',
    'entry/src/main/resources/rawfile/skills/html/references/frontend-design.md',
    'entry/src/main/resources/rawfile/skills/html/references/visual-techniques.md',
    'entry/src/main/resources/rawfile/skills/html/references/3d-design.md',
    'entry/src/main/resources/rawfile/skills/html/references/chart-atlas.md',
    'entry/src/main/resources/rawfile/skills/paper-reviewer/SKILL.md',
    'entry/src/main/resources/rawfile/skills/paper-reviewer/references/review-criteria.md',
    'entry/src/main/resources/rawfile/skills/paper-reviewer/references/review-template.md',
    'entry/src/main/resources/rawfile/skills/review-agent/SKILL.md',
    'entry/src/main/resources/rawfile/skills/paper-rebuttal/SKILL.md',
    'entry/src/main/resources/rawfile/skills/paper-rebuttal/references/comment-taxonomy.md',
    'entry/src/main/resources/rawfile/skills/paper-rebuttal/references/rebuttal-writing-guide.md',
    'entry/src/main/resources/rawfile/skills/paper-rebuttal/references/response-template.md',
    'entry/src/main/resources/rawfile/skills/research-lineage-map/SKILL.md',
    'entry/src/main/resources/rawfile/skills/research-lineage-map/references/mermaid-patterns.md',
    'entry/src/main/resources/rawfile/skills/research-lineage-map/references/output-template.md',
    'entry/src/main/resources/rawfile/skills/marketing-plan/SKILL.md',
    'entry/src/main/resources/rawfile/skills/marketing-plan/references/hotspot-guide.md',
    'entry/src/main/resources/rawfile/skills/marketing-plan/references/image-methodology.md',
    'entry/src/main/resources/rawfile/skills/marketing-plan/references/output-format.md',
    'entry/src/main/resources/rawfile/skills/marketing-plan/references/planning-methodology.md',
    'entry/src/main/resources/rawfile/skills/reference-audit/SKILL.md',
    'entry/src/main/resources/rawfile/skills/reference-audit/assets/report-template.md',
    'entry/src/main/resources/rawfile/skills/paper-close-reading/SKILL.md',
    'entry/src/main/resources/rawfile/skills/paper-close-reading/assets/report-template.md',
    'entry/src/main/resources/rawfile/skills/khazix-writer/SKILL.md',
    'entry/src/main/resources/rawfile/skills/khazix-writer/references/content_methodology.md',
    'entry/src/main/resources/rawfile/skills/khazix-writer/references/style_examples.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/SKILL.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/genre-guide/composite.writing-guide.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/genre-guide/lark-doc.writing-guide.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/genre-guide/short-video.writing-guide.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/genre-guide/wechat.writing-guide.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/genre-guide/xhs.writing-guide.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/short-video.samples/creative-playbook.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/short-video.samples/output-format.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/short-video.samples/research-workflow.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/short-video.samples/visual-storyboard.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/Internet-search-rules.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/Layout-and-illustration-requirements.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/writing-styles/cognitive-opinion.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/writing-styles/emotional-healing.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/writing-styles/narrative-nonfiction.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/writing-styles/news-hotspot.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/wechat.samples/writing-styles/professional-explainer.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.creation-methodology.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.creation-methods.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.hotspot-guide.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.image-cover-methodology.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.image-design-methods.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.image-design-methods-2.md',
    'entry/src/main/resources/rawfile/skills/newmedia-writing/references/xhs.samples/xhs-note-proposal.samples.output-format.md',
    'entry/src/main/resources/rawfile/skills/marketing-material-review/SKILL.md',
    'entry/src/main/resources/rawfile/skills/patent-drafting/SKILL.md',
    'entry/src/main/resources/rawfile/skills/patent-drafting/README.md',
    'entry/src/main/resources/rawfile/skills/patent-drafting/references/writing-style.md',
    'entry/src/main/resources/rawfile/skills/patent-drafting/sub-skills/claims/SKILL.md',
    'entry/src/main/resources/rawfile/skills/patent-drafting/sub-skills/intake-audit/SKILL.md',
    'entry/src/main/resources/rawfile/skills/patent-drafting/sub-skills/specification/SKILL.md',
    'entry/src/main/resources/rawfile/skills/sentiment-tracker/SKILL.md',
    'entry/src/main/resources/rawfile/skills/sentiment-tracker/references/evaluation-set.md',
    'entry/src/main/resources/rawfile/skills/sentiment-tracker/references/twitter-guide.md',
    'entry/src/main/resources/rawfile/skills/sentiment-tracker/references/weibo-guide.md',
    'entry/src/main/resources/rawfile/skills/journal-format/SKILL.md',
    'entry/src/main/resources/rawfile/skills/journal-format/SKILL-2.md',
    'entry/src/main/resources/rawfile/skills/journal-format/SKILL-3.md',
    'entry/src/main/resources/rawfile/skills/journal-format/SKILL-4.md',
    'entry/src/main/resources/rawfile/skills/journal-format/SKILL-5.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/equations-tables-sections.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/equations-tables-sections-2.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/equations-tables-sections-3.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/explicit-postprocess.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/preservation-rules.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/preservation-rules-2.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/preservation-rules-3.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/references-numbering-superscript.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/references-numbering-superscript-2.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/style-routing.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/style-routing-2.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/style-routing-3.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/style-routing-4.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/style-routing-5.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/template-distill-render-qa.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/template-distill-render-qa-2.md',
    'entry/src/main/resources/rawfile/skills/journal-format/references/template-distill-render-qa-3.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/SKILL.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/academic-grant-guide.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/academic-scenarios-guide.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/anti-fabrication-rules.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/literature-review-guide.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/output-and-validation.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/research-logic-design.md',
    'entry/src/main/resources/rawfile/skills/research-proposal/references/workflow-checkpoints.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/SKILL.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/analysis-framework.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/data-collection-protocol.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/data-grading-and-citation.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/industry-structure-playbooks.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/insight-spine.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/lark-doc-report-standard.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/report-finalization.md',
    'entry/src/main/resources/rawfile/skills/industry-analysis/references/task-router.md',
    'README.md',
    'README_EN.md',
]
lines = []
ok_all = True
for f in files:
    t = open(f, encoding='utf-8').read()
    fences = sum(1 for ln in t.splitlines() if ln.strip().startswith('```'))
    if 'README' in f:
        status = 'fences %d %s' % (fences, 'BALANCED' if fences % 2 == 0 else 'UNBALANCED!')
        if fences % 2 != 0:
            ok_all = False
    else:
        too_long = len(t) > 12000
        status = '%d chars %s (fences %d %s)' % (len(t), 'TOO LONG!' if too_long else 'OK',
                                                 fences, 'BALANCED' if fences % 2 == 0 else 'UNBALANCED!')
        if too_long or fences % 2 != 0:
            ok_all = False
    lines.append('%s -> %s' % (f, status))
lines.append('ALL OK' if ok_all else 'PROBLEMS FOUND')
open(os.path.join('test', 'pptx-harness', '_docsize.txt'), 'w', encoding='utf-8').write('\n'.join(lines))
